package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * Arbolopciones generated by hbm2java
 */
public class Arbolopciones implements java.io.Serializable {

	private ArbolopcionesId id;

	public Arbolopciones() {
	}

	public Arbolopciones(ArbolopcionesId id) {
		this.id = id;
	}

	public ArbolopcionesId getId() {
		return this.id;
	}

	public void setId(ArbolopcionesId id) {
		this.id = id;
	}

}
