package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * ArbolopcionesId generated by hbm2java
 */
public class ArbolopcionesId implements java.io.Serializable {

	private int padre;
	private int hijo;
	private int profundidad;

	public ArbolopcionesId() {
	}

	public ArbolopcionesId(int padre, int hijo, int profundidad) {
		this.padre = padre;
		this.hijo = hijo;
		this.profundidad = profundidad;
	}

	public int getPadre() {
		return this.padre;
	}

	public void setPadre(int padre) {
		this.padre = padre;
	}

	public int getHijo() {
		return this.hijo;
	}

	public void setHijo(int hijo) {
		this.hijo = hijo;
	}

	public int getProfundidad() {
		return this.profundidad;
	}

	public void setProfundidad(int profundidad) {
		this.profundidad = profundidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArbolopcionesId))
			return false;
		ArbolopcionesId castOther = (ArbolopcionesId) other;

		return (this.getPadre() == castOther.getPadre()) && (this.getHijo() == castOther.getHijo())
				&& (this.getProfundidad() == castOther.getProfundidad());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPadre();
		result = 37 * result + this.getHijo();
		result = 37 * result + this.getProfundidad();
		return result;
	}

}
