package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * AulasrecursosId generated by hbm2java
 */
public class AulasrecursosId implements java.io.Serializable {

	private String idAula;
	private int idRecurso;

	public AulasrecursosId() {
	}

	public AulasrecursosId(String idAula, int idRecurso) {
		this.idAula = idAula;
		this.idRecurso = idRecurso;
	}

	public String getIdAula() {
		return this.idAula;
	}

	public void setIdAula(String idAula) {
		this.idAula = idAula;
	}

	public int getIdRecurso() {
		return this.idRecurso;
	}

	public void setIdRecurso(int idRecurso) {
		this.idRecurso = idRecurso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AulasrecursosId))
			return false;
		AulasrecursosId castOther = (AulasrecursosId) other;

		return ((this.getIdAula() == castOther.getIdAula()) || (this.getIdAula() != null
				&& castOther.getIdAula() != null && this.getIdAula().equals(castOther.getIdAula())))
				&& (this.getIdRecurso() == castOther.getIdRecurso());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdAula() == null ? 0 : this.getIdAula().hashCode());
		result = 37 * result + this.getIdRecurso();
		return result;
	}

}
