package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aulas generated by hbm2java
 */
public class Aulas implements java.io.Serializable {

	private String idAula;
	private String aula;
	private Tipoaula tipoaula;
	private int asientos;
	private String comentarios;
	private Estados estados;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Aulas() {
	}

	public Aulas(String idAula, String aula, Tipoaula tipoaula, int asientos, String comentarios, 
			Estados estados, Date fechaCreacion, int usuarioCrea) {
		this.idAula = idAula;
		this.aula = aula;
		this.asientos = asientos;
		this.comentarios = comentarios;
		this.tipoaula = tipoaula;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Aulas(String idAula, String aula, Tipoaula tipoaula, int asientos, String comentarios, 
			Estados estados, Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.idAula = idAula;
		this.aula = aula;
		this.asientos = asientos;
		this.comentarios = comentarios;
		this.tipoaula = tipoaula;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public String getIdAula() {
		return this.idAula;
	}

	public void setIdAula(String idAula) {
		this.idAula = idAula;
	}

	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}
	
	public Tipoaula getTipoaula() {
		return tipoaula;
	}

	public void setTipoaula(Tipoaula tipoaula) {
		this.tipoaula = tipoaula;
	}

	public int getAsientos() {
		return this.asientos;
	}

	public void setAsientos(int asientos) {
		this.asientos = asientos;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}
}
