package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Dispprofesores generated by hbm2java
 */
public class Dispprofesores implements java.io.Serializable {

	private DispprofesoresId id;
	private Dias dias;
	private Profesores profesores;
	private Horas horas;
	private char disponible;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Dispprofesores() {
	}

	public Dispprofesores(DispprofesoresId id, Dias dias, Profesores profesores, Horas horas, char disponible,
			char estado, Date fechaCreacion, int usuarioCrea) {
		this.id = id;
		this.dias = dias;
		this.profesores = profesores;
		this.horas = horas;
		this.disponible = disponible;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Dispprofesores(DispprofesoresId id, Dias dias, Profesores profesores, Horas horas, char disponible,
			char estado, Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.id = id;
		this.dias = dias;
		this.profesores = profesores;
		this.horas = horas;
		this.disponible = disponible;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public DispprofesoresId getId() {
		return this.id;
	}

	public void setId(DispprofesoresId id) {
		this.id = id;
	}

	public Dias getDias() {
		return this.dias;
	}

	public void setDias(Dias dias) {
		this.dias = dias;
	}

	public Profesores getProfesores() {
		return this.profesores;
	}

	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	public Horas getHoras() {
		return this.horas;
	}

	public void setHoras(Horas horas) {
		this.horas = horas;
	}

	public char getDisponible() {
		return this.disponible;
	}

	public void setDisponible(char disponible) {
		this.disponible = disponible;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
