package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * DispprofesoresId generated by hbm2java
 */
public class DispprofesoresId implements java.io.Serializable {

	private int idDispProfesor;
	private int idProfesor;
	private String idDia;
	private int idHora;

	public DispprofesoresId() {
	}

	public DispprofesoresId(int idDispProfesor, int idProfesor, String idDia, int idHora) {
		this.idDispProfesor = idDispProfesor;
		this.idProfesor = idProfesor;
		this.idDia = idDia;
		this.idHora = idHora;
	}

	public int getIdDispProfesor() {
		return this.idDispProfesor;
	}

	public void setIdDispProfesor(int idDispProfesor) {
		this.idDispProfesor = idDispProfesor;
	}

	public int getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(int idProfesor) {
		this.idProfesor = idProfesor;
	}

	public String getIdDia() {
		return this.idDia;
	}

	public void setIdDia(String idDia) {
		this.idDia = idDia;
	}

	public int getIdHora() {
		return this.idHora;
	}

	public void setIdHora(int idHora) {
		this.idHora = idHora;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DispprofesoresId))
			return false;
		DispprofesoresId castOther = (DispprofesoresId) other;

		return (this.getIdDispProfesor() == castOther.getIdDispProfesor())
				&& (this.getIdProfesor() == castOther.getIdProfesor())
				&& ((this.getIdDia() == castOther.getIdDia()) || (this.getIdDia() != null
						&& castOther.getIdDia() != null && this.getIdDia().equals(castOther.getIdDia())))
				&& (this.getIdHora() == castOther.getIdHora());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDispProfesor();
		result = 37 * result + this.getIdProfesor();
		result = 37 * result + (getIdDia() == null ? 0 : this.getIdDia().hashCode());
		result = 37 * result + this.getIdHora();
		return result;
	}

}
