package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Horariosdetalle generated by hbm2java
 */
public class Horariosdetalle implements java.io.Serializable {

	private HorariosdetalleId id;
	private Horarioscabecera horarioscabecera;
	private Dias dias;
	private Profesoresmaterias profesoresmaterias;
	private Aulas aulas;
	private Horas horas;
	private String paralelo;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Horariosdetalle() {
	}

	public Horariosdetalle(HorariosdetalleId id, Horarioscabecera horarioscabecera, Dias dias,
			Profesoresmaterias profesoresmaterias, Aulas aulas, Horas horas, String paralelo, char estado,
			Date fechaCreacion, int usuarioCrea) {
		this.id = id;
		this.horarioscabecera = horarioscabecera;
		this.dias = dias;
		this.profesoresmaterias = profesoresmaterias;
		this.aulas = aulas;
		this.horas = horas;
		this.paralelo = paralelo;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Horariosdetalle(HorariosdetalleId id, Horarioscabecera horarioscabecera, Dias dias,
			Profesoresmaterias profesoresmaterias, Aulas aulas, Horas horas, String paralelo, char estado,
			Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.id = id;
		this.horarioscabecera = horarioscabecera;
		this.dias = dias;
		this.profesoresmaterias = profesoresmaterias;
		this.aulas = aulas;
		this.horas = horas;
		this.paralelo = paralelo;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public HorariosdetalleId getId() {
		return this.id;
	}

	public void setId(HorariosdetalleId id) {
		this.id = id;
	}

	public Horarioscabecera getHorarioscabecera() {
		return this.horarioscabecera;
	}

	public void setHorarioscabecera(Horarioscabecera horarioscabecera) {
		this.horarioscabecera = horarioscabecera;
	}

	public Dias getDias() {
		return this.dias;
	}

	public void setDias(Dias dias) {
		this.dias = dias;
	}

	public Profesoresmaterias getProfesoresmaterias() {
		return this.profesoresmaterias;
	}

	public void setProfesoresmaterias(Profesoresmaterias profesoresmaterias) {
		this.profesoresmaterias = profesoresmaterias;
	}

	public Aulas getAulas() {
		return this.aulas;
	}

	public void setAulas(Aulas aulas) {
		this.aulas = aulas;
	}

	public Horas getHoras() {
		return this.horas;
	}

	public void setHoras(Horas horas) {
		this.horas = horas;
	}

	public String getParalelo() {
		return this.paralelo;
	}

	public void setParalelo(String paralelo) {
		this.paralelo = paralelo;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
