package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Horariosdetalletmp generated by hbm2java
 */
public class Horariosdetalletmp implements java.io.Serializable {

	private Integer idHorariosDetTmp;
	private int idHorarioCabTmp;
	private int idProfesor;
	private String idMateria;
	private String idCurso;
	private String paralelo;
	private String idAula;
	private String idDia;
	private int idHora;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Horariosdetalletmp() {
	}

	public Horariosdetalletmp(int idHorarioCabTmp, int idProfesor, String idMateria, String idCurso, String paralelo,
			String idAula, String idDia, int idHora, char estado, Date fechaCreacion, int usuarioCrea) {
		this.idHorarioCabTmp = idHorarioCabTmp;
		this.idProfesor = idProfesor;
		this.idMateria = idMateria;
		this.idCurso = idCurso;
		this.paralelo = paralelo;
		this.idAula = idAula;
		this.idDia = idDia;
		this.idHora = idHora;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Horariosdetalletmp(int idHorarioCabTmp, int idProfesor, String idMateria, String idCurso, String paralelo,
			String idAula, String idDia, int idHora, char estado, Date fechaCreacion, int usuarioCrea,
			Date fechaModificacion, Integer usuarioModifica) {
		this.idHorarioCabTmp = idHorarioCabTmp;
		this.idProfesor = idProfesor;
		this.idMateria = idMateria;
		this.idCurso = idCurso;
		this.paralelo = paralelo;
		this.idAula = idAula;
		this.idDia = idDia;
		this.idHora = idHora;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public Integer getIdHorariosDetTmp() {
		return this.idHorariosDetTmp;
	}

	public void setIdHorariosDetTmp(Integer idHorariosDetTmp) {
		this.idHorariosDetTmp = idHorariosDetTmp;
	}

	public int getIdHorarioCabTmp() {
		return this.idHorarioCabTmp;
	}

	public void setIdHorarioCabTmp(int idHorarioCabTmp) {
		this.idHorarioCabTmp = idHorarioCabTmp;
	}

	public int getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(int idProfesor) {
		this.idProfesor = idProfesor;
	}

	public String getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(String idMateria) {
		this.idMateria = idMateria;
	}

	public String getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(String idCurso) {
		this.idCurso = idCurso;
	}

	public String getParalelo() {
		return this.paralelo;
	}

	public void setParalelo(String paralelo) {
		this.paralelo = paralelo;
	}

	public String getIdAula() {
		return this.idAula;
	}

	public void setIdAula(String idAula) {
		this.idAula = idAula;
	}

	public String getIdDia() {
		return this.idDia;
	}

	public void setIdDia(String idDia) {
		this.idDia = idDia;
	}

	public int getIdHora() {
		return this.idHora;
	}

	public void setIdHora(int idHora) {
		this.idHora = idHora;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
