package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * HorariosdetalleId generated by hbm2java
 */
public class HorariosdetalleId implements java.io.Serializable {

	private int idHorarioDet;
	private Horarioscabecera horarioscabecera;

	public HorariosdetalleId() {
	}

	public HorariosdetalleId(int idHorarioDet, Horarioscabecera horarioscabecera) {
		super();
		this.idHorarioDet = idHorarioDet;
		this.horarioscabecera = horarioscabecera;
	}

	public int getIdHorarioDet() {
		return idHorarioDet;
	}

	public void setIdHorarioDet(int idHorarioDet) {
		this.idHorarioDet = idHorarioDet;
	}

	public Horarioscabecera getHorarioscabecera() {
		return horarioscabecera;
	}

	public void setHorarioscabecera(Horarioscabecera horarioscabecera) {
		this.horarioscabecera = horarioscabecera;
	}

}
