package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Horariosdetalle generated by hbm2java
 */
public class Horariosdetalle implements java.io.Serializable {

	private HorariosdetalleId id;
	private Profesoresmaterias profesoresmaterias;
	private Dispprofesores dispprofesores;
	private Aulas aulas;
	private String paralelo;
	private Estados estados;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Horariosdetalle() {
	}

	public Horariosdetalle(HorariosdetalleId id, Profesoresmaterias profesoresmaterias, 
			Dispprofesores dispprofesores, Aulas aulas, String paralelo, Estados estados, 
			Date fechaCreacion, int usuarioCrea) {
		this.id = id;
		this.profesoresmaterias = profesoresmaterias;
		this.dispprofesores = dispprofesores;
		this.aulas = aulas;
		this.paralelo = paralelo;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Horariosdetalle(HorariosdetalleId id, Profesoresmaterias profesoresmaterias, 
			Dispprofesores dispprofesores, Aulas aulas, String paralelo, Estados estados,
			Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.id = id;
		this.profesoresmaterias = profesoresmaterias;
		this.dispprofesores = dispprofesores;
		this.aulas = aulas;
		this.paralelo = paralelo;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public HorariosdetalleId getId() {
		return this.id;
	}

	public void setId(HorariosdetalleId id) {
		this.id = id;
	}

	public Profesoresmaterias getProfesoresmaterias() {
		return this.profesoresmaterias;
	}

	public void setProfesoresmaterias(Profesoresmaterias profesoresmaterias) {
		this.profesoresmaterias = profesoresmaterias;
	}

	public Dispprofesores getDispprofesores() {
		return dispprofesores;
	}

	public void setDispprofesores(Dispprofesores dispprofesores) {
		this.dispprofesores = dispprofesores;
	}

	public Aulas getAulas() {
		return this.aulas;
	}

	public void setAulas(Aulas aulas) {
		this.aulas = aulas;
	}

	public String getParalelo() {
		return this.paralelo;
	}

	public void setParalelo(String paralelo) {
		this.paralelo = paralelo;
	}

	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estado) {
		this.estados = estados;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
