package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * HorariosdetalleId generated by hbm2java
 */
public class HorariosdetalleId implements java.io.Serializable {

	private int idHorarioDet;
	private int idHorarioCab;

	public HorariosdetalleId() {
	}

	public HorariosdetalleId(int idHorarioDet, int idHorarioCab) {
		this.idHorarioDet = idHorarioDet;
		this.idHorarioCab = idHorarioCab;
	}

	public int getIdHorarioDet() {
		return this.idHorarioDet;
	}

	public void setIdHorarioDet(int idHorarioDet) {
		this.idHorarioDet = idHorarioDet;
	}

	public int getIdHorarioCab() {
		return this.idHorarioCab;
	}

	public void setIdHorarioCab(int idHorarioCab) {
		this.idHorarioCab = idHorarioCab;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HorariosdetalleId))
			return false;
		HorariosdetalleId castOther = (HorariosdetalleId) other;

		return (this.getIdHorarioDet() == castOther.getIdHorarioDet())
				&& (this.getIdHorarioCab() == castOther.getIdHorarioCab());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdHorarioDet();
		result = 37 * result + this.getIdHorarioCab();
		return result;
	}

}
