package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias implements java.io.Serializable {

	private String idMateria;
	private String materia;
	private Date duracionClase;
	private Date horasSemana;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Materias() {
	}

	public Materias(String idMateria, String materia, Date duracionClase, Date horasSemana, char estado, Date fechaCreacion, int usuarioCrea) {
		this.idMateria = idMateria;
		this.materia = materia;
		this.duracionClase = duracionClase;
		this.horasSemana = horasSemana;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Materias(String idMateria, String materia, Date duracionClase, Date horasSemana, char estado, Date fechaCreacion,
			int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.idMateria = idMateria;
		this.materia = materia;
		this.duracionClase = duracionClase;
		this.horasSemana = horasSemana;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public String getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(String idMateria) {
		this.idMateria = idMateria;
	}

	public String getMateria() {
		return this.materia;
	}

	public void setMateria(String materia) {
		this.materia = materia;
	}

	public Date getDuracionClase() {
		return duracionClase;
	}

	public void setDuracionClase(Date duracionClase) {
		this.duracionClase = duracionClase;
	}

	public Date getHorasSemana() {
		return horasSemana;
	}

	public void setHorasSemana(Date horasSemana) {
		this.horasSemana = horasSemana;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}
	
}
