package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Materiascursos generated by hbm2java
 */
public class Materiascursos implements java.io.Serializable {

	private MateriascursosId id;
	private Materias materias;
	private Cursos cursos;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;
	private Set<Profesoresmaterias> profesoresmateriases = new HashSet<Profesoresmaterias>(0);

	public Materiascursos() {
	}

	public Materiascursos(MateriascursosId id, Materias materias, Cursos cursos, char estado, Date fechaCreacion,
			int usuarioCrea) {
		this.id = id;
		this.materias = materias;
		this.cursos = cursos;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Materiascursos(MateriascursosId id, Materias materias, Cursos cursos, char estado, Date fechaCreacion,
			int usuarioCrea, Date fechaModificacion, Integer usuarioModifica,
			Set<Profesoresmaterias> profesoresmateriases) {
		this.id = id;
		this.materias = materias;
		this.cursos = cursos;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
		this.profesoresmateriases = profesoresmateriases;
	}

	public MateriascursosId getId() {
		return this.id;
	}

	public void setId(MateriascursosId id) {
		this.id = id;
	}

	public Materias getMaterias() {
		return this.materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Set<Profesoresmaterias> getProfesoresmateriases() {
		return this.profesoresmateriases;
	}

	public void setProfesoresmateriases(Set<Profesoresmaterias> profesoresmateriases) {
		this.profesoresmateriases = profesoresmateriases;
	}

}
