package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * MateriasrecursosId generated by hbm2java
 */
public class MateriasrecursosId implements java.io.Serializable {

	private Recursos recursos;
	private Materias materias;

	public MateriasrecursosId() {
	}

	public Recursos getRecursos() {
		return recursos;
	}

	public void setRecursos(Recursos recursos) {
		this.recursos = recursos;
	}

	public Materias getMaterias() {
		return materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}
	
}
