package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * MateriascursosId generated by hbm2java
 */
public class MateriascursosId implements java.io.Serializable {

	private Materias materias;
	private Cursos cursos;

	public MateriascursosId() {
	}
	
	public MateriascursosId(Materias materias, Cursos cursos) {
		super();
		this.materias = materias;
		this.cursos = cursos;
	}

	public Materias getMaterias() {
		return materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	public Cursos getCursos() {
		return cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}
}
