package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Materiasrecursos generated by hbm2java
 */
public class Materiasrecursos implements java.io.Serializable {

	private MateriasrecursosId id;
	private int stockNecesario;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Materiasrecursos() {
	}

	public Materiasrecursos(MateriasrecursosId id, int stockNecesario,
			char estado, Date fechaCreacion, int usuarioCrea) {
		this.id = id;
		this.stockNecesario = stockNecesario;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Materiasrecursos(MateriasrecursosId id, int stockNecesario,
			char estado, Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.id = id;
		this.stockNecesario = stockNecesario;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public MateriasrecursosId getId() {
		return this.id;
	}

	public void setId(MateriasrecursosId id) {
		this.id = id;
	}

	public int getStockNecesario() {
		return this.stockNecesario;
	}

	public void setStockNecesario(int stockNecesario) {
		this.stockNecesario = stockNecesario;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
