package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Materias generated by hbm2java
 */
public class Materias implements java.io.Serializable {

	private String idMateria;
	private String materia;
	private Tipoaula tipoaula;
	private Estados estados;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Materias() {
	}

	public Materias(String idMateria, String materia, Tipoaula tipoaula, Estados estados, Date fechaCreacion, 
			int usuarioCrea) {
		this.idMateria = idMateria;
		this.materia = materia;
		this.tipoaula = tipoaula;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Materias(String idMateria, String materia, Tipoaula tipoaula, Estados estados, Date fechaCreacion, 
			int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.idMateria = idMateria;
		this.materia = materia;
		this.tipoaula = tipoaula;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public String getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(String idMateria) {
		this.idMateria = idMateria;
	}

	public String getMateria() {
		return this.materia;
	}

	public void setMateria(String materia) {
		this.materia = materia;
	}
	
	public Tipoaula getTipoaula() {
		return this.tipoaula;
	}

	public void setTipoaula(Tipoaula tipoaula) {
		this.tipoaula = tipoaula;
	}

	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}
	
}
