package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Materiascursos generated by hbm2java
 */
public class Materiascursos implements java.io.Serializable {

	private MateriascursosId id;
	private int horasSemana;
	private Estados estados;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Materiascursos() {
	}

	public Materiascursos(MateriascursosId id, int horasSemana, Estados estados, Date fechaCreacion,
			int usuarioCrea) {
		this.id = id;
		this.horasSemana = horasSemana;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Materiascursos(MateriascursosId id, int horasSemana, Estados estados, Date fechaCreacion, 
			int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.id = id;
		this.horasSemana = horasSemana;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public MateriascursosId getId() {
		return this.id;
	}

	public void setId(MateriascursosId id) {
		this.id = id;
	}
	
	public int getHorasSemana() {
		return horasSemana;
	}

	public void setHorasSemana(int horasSemana) {
		this.horasSemana = horasSemana;
	}
	
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}
	
}
