package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfilesusuario generated by hbm2java
 */
public class Perfilesusuario implements java.io.Serializable {

	private Integer idPerfilUsuario;
	private String perfil;
	private String comentarios;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
	private Set<Permisosperfiles> permisosperfileses = new HashSet<Permisosperfiles>(0);

	public Perfilesusuario() {
	}

	public Perfilesusuario(String perfil, String comentarios, char estado, Date fechaCreacion, int usuarioCrea) {
		this.perfil = perfil;
		this.comentarios = comentarios;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Perfilesusuario(String perfil, String comentarios, char estado, Date fechaCreacion, int usuarioCrea,
			Date fechaModificacion, Integer usuarioModifica, Set<Usuarios> usuarioses,
			Set<Permisosperfiles> permisosperfileses) {
		this.perfil = perfil;
		this.comentarios = comentarios;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
		this.usuarioses = usuarioses;
		this.permisosperfileses = permisosperfileses;
	}

	public Integer getIdPerfilUsuario() {
		return this.idPerfilUsuario;
	}

	public void setIdPerfilUsuario(Integer idPerfilUsuario) {
		this.idPerfilUsuario = idPerfilUsuario;
	}

	public String getPerfil() {
		return this.perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

	public Set<Permisosperfiles> getPermisosperfileses() {
		return this.permisosperfileses;
	}

	public void setPermisosperfileses(Set<Permisosperfiles> permisosperfileses) {
		this.permisosperfileses = permisosperfileses;
	}

}
