package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Permisosperfiles generated by hbm2java
 */
public class Permisosperfiles implements java.io.Serializable {

	private PermisosperfilesId id;
	private Perfilesusuario perfilesusuario;
	private Permisos permisos;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Permisosperfiles() {
	}

	public Permisosperfiles(PermisosperfilesId id, Perfilesusuario perfilesusuario, Permisos permisos, char estado,
			Date fechaCreacion, int usuarioCrea) {
		this.id = id;
		this.perfilesusuario = perfilesusuario;
		this.permisos = permisos;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Permisosperfiles(PermisosperfilesId id, Perfilesusuario perfilesusuario, Permisos permisos, char estado,
			Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.id = id;
		this.perfilesusuario = perfilesusuario;
		this.permisos = permisos;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public PermisosperfilesId getId() {
		return this.id;
	}

	public void setId(PermisosperfilesId id) {
		this.id = id;
	}

	public Perfilesusuario getPerfilesusuario() {
		return this.perfilesusuario;
	}

	public void setPerfilesusuario(Perfilesusuario perfilesusuario) {
		this.perfilesusuario = perfilesusuario;
	}

	public Permisos getPermisos() {
		return this.permisos;
	}

	public void setPermisos(Permisos permisos) {
		this.permisos = permisos;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
