package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos implements java.io.Serializable {

	private Integer idPermiso;
	private String permiso;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;
	private Set<Opciones> opcioneses = new HashSet<Opciones>(0);
	private Set<Permisosperfiles> permisosperfileses = new HashSet<Permisosperfiles>(0);

	public Permisos() {
	}

	public Permisos(String permiso, char estado, Date fechaCreacion, int usuarioCrea) {
		this.permiso = permiso;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Permisos(String permiso, char estado, Date fechaCreacion, int usuarioCrea, Date fechaModificacion,
			Integer usuarioModifica, Set<Opciones> opcioneses, Set<Permisosperfiles> permisosperfileses) {
		this.permiso = permiso;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
		this.opcioneses = opcioneses;
		this.permisosperfileses = permisosperfileses;
	}

	public Integer getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(Integer idPermiso) {
		this.idPermiso = idPermiso;
	}

	public String getPermiso() {
		return this.permiso;
	}

	public void setPermiso(String permiso) {
		this.permiso = permiso;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Set<Opciones> getOpcioneses() {
		return this.opcioneses;
	}

	public void setOpcioneses(Set<Opciones> opcioneses) {
		this.opcioneses = opcioneses;
	}

	public Set<Permisosperfiles> getPermisosperfileses() {
		return this.permisosperfileses;
	}

	public void setPermisosperfileses(Set<Permisosperfiles> permisosperfileses) {
		this.permisosperfileses = permisosperfileses;
	}

}
