package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

/**
 * PermisosperfilesId generated by hbm2java
 */
public class PermisosperfilesId implements java.io.Serializable {

	private Perfilesusuario perfilesusuario;
	private Permisos permisos;

	public PermisosperfilesId() {
	}

	public PermisosperfilesId(Perfilesusuario perfilesusuario, Permisos permisos) {
		super();
		this.perfilesusuario = perfilesusuario;
		this.permisos = permisos;
	}

	public Perfilesusuario getPerfilesusuario() {
		return perfilesusuario;
	}

	public void setPerfilesusuario(Perfilesusuario perfilesusuario) {
		this.perfilesusuario = perfilesusuario;
	}

	public Permisos getPermisos() {
		return permisos;
	}

	public void setPermisos(Permisos permisos) {
		this.permisos = permisos;
	}
	
}
