package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesoresmaterias generated by hbm2java
 */
public class Profesoresmaterias implements java.io.Serializable {

	private ProfesoresmateriasId id;
	private Profesores profesores;
	private Materiascursos materiascursos;
	private char estado;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;
	private Set<Horariosdetalle> horariosdetalles = new HashSet<Horariosdetalle>(0);

	public Profesoresmaterias() {
	}

	public Profesoresmaterias(ProfesoresmateriasId id, Profesores profesores, Materiascursos materiascursos,
			char estado, Date fechaCreacion, int usuarioCrea) {
		this.id = id;
		this.profesores = profesores;
		this.materiascursos = materiascursos;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Profesoresmaterias(ProfesoresmateriasId id, Profesores profesores, Materiascursos materiascursos,
			char estado, Date fechaCreacion, int usuarioCrea, Date fechaModificacion, Integer usuarioModifica,
			Set<Horariosdetalle> horariosdetalles) {
		this.id = id;
		this.profesores = profesores;
		this.materiascursos = materiascursos;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
		this.horariosdetalles = horariosdetalles;
	}

	public ProfesoresmateriasId getId() {
		return this.id;
	}

	public void setId(ProfesoresmateriasId id) {
		this.id = id;
	}

	public Profesores getProfesores() {
		return this.profesores;
	}

	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	public Materiascursos getMateriascursos() {
		return this.materiascursos;
	}

	public void setMateriascursos(Materiascursos materiascursos) {
		this.materiascursos = materiascursos;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Set<Horariosdetalle> getHorariosdetalles() {
		return this.horariosdetalles;
	}

	public void setHorariosdetalles(Set<Horariosdetalle> horariosdetalles) {
		this.horariosdetalles = horariosdetalles;
	}

}
