package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores implements java.io.Serializable {

	private Integer idProfesor;
	private String profesor;
	private String titulo;
	private int maxHorasPorSemana;
	private Estados estados;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Profesores() {
	}

	public Profesores(String profesor, String titulo, int maxHorasPorSemana, Estados estados, Date fechaCreacion, int usuarioCrea) {
		this.profesor = profesor;
		this.titulo = titulo;
		this.maxHorasPorSemana = maxHorasPorSemana;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Profesores(String profesor, String titulo, int maxHorasPorSemana, Estados estados, Date fechaCreacion,
			int usuarioCrea, Date fechaModificacion, Integer usuarioModifica) {
		this.profesor = profesor;
		this.titulo = titulo;
		this.maxHorasPorSemana = maxHorasPorSemana;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public Integer getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(Integer idProfesor) {
		this.idProfesor = idProfesor;
	}

	public String getProfesor() {
		return this.profesor;
	}

	public void setProfesor(String profesor) {
		this.profesor = profesor;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getMaxHorasPorSemana() {
		return this.maxHorasPorSemana;
	}

	public void setMaxHorasPorSemana(int maxHorasPorSemana) {
		this.maxHorasPorSemana = maxHorasPorSemana;
	}

	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
