package entidades;
// Generated Jul 4, 2016 12:16:49 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schollaryear generated by hbm2java
 */
public class Schollaryear implements java.io.Serializable {

	private Integer idSchoolarYear;
	private String schollarYear;
	private Date fechaInicio;
	private Date fechaFin;
	private Date duracionClase;
	private int maxHorasSemanaProfesor;
	private Estados estados;
	private Date fechaCreacion;
	private int usuarioCrea;
	private Date fechaModificacion;
	private Integer usuarioModifica;

	public Schollaryear() {
	}

	public Schollaryear(String schollarYear, Date fechaInicio, Date fechaFin, Date duracionClase, 
			int maxHorasSemanaProfesor, Estados estados, Date fechaCreacion, int usuarioCrea) {
		this.schollarYear = schollarYear;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.duracionClase = duracionClase;
		this.maxHorasSemanaProfesor = maxHorasSemanaProfesor;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
	}

	public Schollaryear(String schollarYear, Date fechaInicio, Date fechaFin, Date duracionClase, 
			int maxHorasSemanaProfesor, Estados estados, Date fechaCreacion, int usuarioCrea, Date fechaModificacion, 
			Integer usuarioModifica) {
		this.schollarYear = schollarYear;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.duracionClase = duracionClase;
		this.maxHorasSemanaProfesor = maxHorasSemanaProfesor;
		this.estados = estados;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCrea = usuarioCrea;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModifica = usuarioModifica;
	}

	public Integer getIdSchoolarYear() {
		return this.idSchoolarYear;
	}

	public void setIdSchoolarYear(Integer idSchoolarYear) {
		this.idSchoolarYear = idSchoolarYear;
	}

	public String getSchollarYear() {
		return this.schollarYear;
	}

	public void setSchollarYear(String schollarYear) {
		this.schollarYear = schollarYear;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
	public Date getDuracionClase() {
		return duracionClase;
	}

	public void setDuracionClase(Date duracionClase) {
		this.duracionClase = duracionClase;
	}
	
	public int getMaxHorasSemanaProfesor() {
		return this.maxHorasSemanaProfesor;
	}
	
	public void setMaxHorasSemanaProfesor(int maxHorasSemanaProfesor) {
		this.maxHorasSemanaProfesor = maxHorasSemanaProfesor;
	}
	
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public int getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(int usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Integer getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(Integer usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

}
